# Generated by Django 3.0.6 on 2020-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phoneNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
