# Generated by Django 3.0.6 on 2020-05-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200527_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'Food Delivery'), (1, 'Assignment Complete')], verbose_name='Category')),
                ('description', models.TextField(help_text='Write a little bit about the service', verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='city',
            field=models.CharField(max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='customer',
            field=models.BooleanField(choices=[(True, 'Customer'), (False, 'Service Provider')], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phoneNumber',
            field=models.IntegerField(unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='pincode',
            field=models.IntegerField(verbose_name='Pin Code'),
        ),
    ]
