# Generated by Django 3.0.6 on 2020-05-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200527_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(choices=[(True, 'Available'), (False, 'Busy')], default=False, verbose_name='Service Completed'),
        ),
    ]
