# Generated by Django 3.0.6 on 2020-05-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200527_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='website.UserDetail', verbose_name='Service Provider'),
        ),
    ]
