# Generated by Django 3.0.6 on 2020-06-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200530_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='provider',
        ),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Service Completed'),
        ),
    ]
