# Generated by Django 3.0.6 on 2020-06-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0010_auto_20200604_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True,
                                      verbose_name='Service Not Completed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.ServiceDetail',
                                    verbose_name='Service Provided'),
        ),
    ]
